name: Build

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        repository: fifomori/nwcompat
        path: app/src/main/assets
    - run: ls -R app/src/main/assets
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle
    - run: chmod +x gradlew

    - uses: mobiledevops/secret-to-file-action@v1
      with:
        base64-encoded-secret: ${{ secrets.KEYSTORE }}
        filename: keystore
        working-directory: '~'
  
    - env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleDebug\
        -Pandroid.injected.signing.store.file="~/keystore"\
        -Pandroid.injected.signing.store.password="$STORE_PASSWORD"\
        -Pandroid.injected.signing.key.alias="key0"\
        -Pandroid.injected.signing.key.password="$KEY_PASSWORD"
  
    - uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/release/app-debug.apk
