name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download apk
        uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
        with:
          url: https://nightly.link/fifomori/android/workflows/build/main/app-debug.apk.zip
          target: download/
          retry-times: 3

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: download/app-debug.apk.zip
          makeLatest: true
          prerelease: ${{ endsWith(github.event.ref, '-beta') }}
